version: 1.0

node: "node2"
location: "YOUR_HOST_IP"
grpc_port: 50050
use_tls: false
disable_report: true

# certificate:
#   root_ca: "/tmp/cert/ca.crt"
#   key: "/tmp/cert/node2.key"
#   cert: "/tmp/cert/node2.crt"

proxy_server:
  mode: "grpc"
  ip:  "YOUR_HOST_IP"
  port: 50050
  use_tls: false

meta_service:
  mode: "grpc"
  ip: "YOUR_HOST_IP"
  port: 9099
  use_tls: false

datasets:
  # ABY3 LR test case datasets
  - description: "train_party_2"
    model: "csv"
    source: "data/train_party_2.csv"
  - description: "test_party_2"
    model: "csv"
    source: "data/test_party_2.csv"

  # FL binclass
  - description: "binclass_vfl_train_guest"
    model: "csv"
    source: "data/FL/binclass/vfl/train/guest.csv"
  - description: "binclass_vfl_test_guest"
    model: "csv"
    source: "data/FL/binclass/vfl/test/guest.csv"
  - description: "binclass_hfl_train_client2"
    model: "csv"
    source: "data/FL/binclass/hfl/train/client2.csv"
  - description: "binclass_hfl_test_client2"
    model: "csv"
    source: "data/FL/binclass/hfl/test/client2.csv"

  # FL multiclass
  - description: "multiclass_vfl_train_guest"
    model: "csv"
    source: "data/FL/multiclass/vfl/train/guest.csv"
  - description: "multiclass_vfl_test_guest"
    model: "csv"
    source: "data/FL/multiclass/vfl/test/guest.csv"
  - description: "multiclass_hfl_train_client2"
    model: "csv"
    source: "data/FL/multiclass/hfl/train/client2.csv"
  - description: "multiclass_hfl_test_client1"
    model: "csv"
    source: "data/FL/multiclass/hfl/test/client2.csv"

  # FL regression
  - description: "regression_vfl_train_guest"
    model: "csv"
    source: "data/FL/regression/vfl/train/guest.csv"
  - description: "regression_vfl_test_guest"
    model: "csv"
    source: "data/FL/regression/vfl/test/guest.csv"
  - description: "regression_hfl_train_client2"
    model: "csv"
    source: "data/FL/regression/hfl/train/client2.csv"
  - description: "regression_hfl_test_client2"
    model: "csv"
    source: "data/FL/regression/hfl/test/client2.csv"

  # FL mnist image classification
  - description: "mnist_train_client2"
    model: "image"
    image_dir: "data/FL/mnist/train/client2.zip"
    annotations_file: "data/FL/mnist/train/client2_annotations.csv"
  - description: "mnist_test_client2"
    model: "image"
    image_dir: "data/FL/mnist/test/client2.zip"
    annotations_file: "data/FL/mnist/test/client2_annotations.csv"

  # FL preprocess
  - description: "preprocess_vfl_train_guest"
    model: "csv"
    source: "data/FL/preprocess/vfl/train/guest.csv"
  - description: "preprocess_vfl_test_guest"
    model: "csv"
    source: "data/FL/preprocess/vfl/test/guest.csv"
  - description: "preprocess_hfl_train_client2"
    model: "csv"
    source: "data/FL/preprocess/hfl/train/client2.csv"
  - description: "preprocess_hfl_test_client2"
    model: "csv"
    source: "data/FL/preprocess/hfl/test/client2.csv"

  # MPC statistics & arithmetic
  - description: "mpc_statistics_2"
    model: "csv"
    source: "data/mpc_test.csv"
  - description: "mpc_arithmetic_2"
    model: "csv"
    source: "data/mpc_arithmetic_2.csv"

  # no meaningful dataset, just used to represent this party
  - description: "FAKE_DATA_PARTY_2"
    model: "csv"
    source: "data/FL/fake.csv"
