version: 1.0

node: "node1"
location: "YOUR_HOST_IP"
grpc_port: 50050
use_tls: false

disable_report: true
# certificate:
#   root_ca: "/tmp/cert/ca.crt"
#   key: "/tmp/cert/node1.key"
#   cert: "/tmp/cert/node1.crt"

proxy_server:
  mode: "grpc"
  ip:  "YOUR_HOST_IP"
  port: 50050
  use_tls: false

meta_service:
  mode: "grpc"
  ip: "YOUR_HOST_IP"
  port: 9099
  use_tls: false

datasets:
  # ABY3 LR test case datasets
  - description: "train_party_1"
    model: "csv"
    source: "data/train_party_1.csv"
  - description: "test_party_1"
    model: "csv"
    source: "data/test_party_1.csv"

  # PIR test case dataset
  - description: "pir_server_data"
    model: "csv"
    source: "data/pir_server.csv"

  # keyword PIR test case dataset
  - description: "keyword_pir_server_data"
    model: "csv"
    source: "data/keyword_pir_server.csv"
  # # service based pir dataset
  # - description: "keyword_pir_server_data"
  #   model: "service"
  #   connect_mode: "grpc"
  #   ip: "127.0.0.1"
  #   port: 60051
  #   use_tls: false
  #   schema:
  #     - name: label1
  #       type: 13
  #     - name: label2
  #       type: 13
  #     - name: label3
  #       type: 13
  #     - name: label4
  #       type: 13

  # PSI test case dataset
  - description: "psi_server_data"
    model: "csv"
    source: "data/server_e.csv"

  - description: "psi_server_data_db"
    model: "sqlite"
    table_name: "psi_server_data"
    source: "data/server_e.db3"

  # FL binclass
  - description: "binclass_vfl_train_host"
    model: "csv"
    source: "data/FL/binclass/vfl/train/host.csv"
  - description: "binclass_vfl_test_host"
    model: "csv"
    source: "data/FL/binclass/vfl/test/host.csv"
  - description: "binclass_hfl_train_client1"
    model: "csv"
    source: "data/FL/binclass/hfl/train/client1.csv"
  - description: "binclass_hfl_test_client1"
    model: "csv"
    source: "data/FL/binclass/hfl/test/client1.csv"

  # FL multiclass
  - description: "multiclass_vfl_train_host"
    model: "csv"
    source: "data/FL/multiclass/vfl/train/host.csv"
  - description: "multiclass_vfl_test_host"
    model: "csv"
    source: "data/FL/multiclass/vfl/test/host.csv"
  - description: "multiclass_hfl_train_client1"
    model: "csv"
    source: "data/FL/multiclass/hfl/train/client1.csv"
  - description: "multiclass_hfl_test_client1"
    model: "csv"
    source: "data/FL/multiclass/hfl/test/client1.csv"

  # FL regression
  - description: "regression_vfl_train_host"
    model: "csv"
    source: "data/FL/regression/vfl/train/host.csv"
  - description: "regression_vfl_test_host"
    model: "csv"
    source: "data/FL/regression/vfl/test/host.csv"
  - description: "regression_hfl_train_client1"
    model: "csv"
    source: "data/FL/regression/hfl/train/client1.csv"
  - description: "regression_hfl_test_client1"
    model: "csv"
    source: "data/FL/regression/hfl/test/client1.csv"

  # FL mnist image classification
  - description: "mnist_train_client1"
    model: "image"
    image_dir: "data/FL/mnist/train/client1.zip"
    annotations_file: "data/FL/mnist/train/client1_annotations.csv"
  - description: "mnist_test_client1"
    model: "image"
    image_dir: "data/FL/mnist/test/client1.zip"
    annotations_file: "data/FL/mnist/test/client1_annotations.csv"

  # FL preprocess
  - description: "preprocess_vfl_train_host"
    model: "csv"
    source: "data/FL/preprocess/vfl/train/host.csv"
  - description: "preprocess_vfl_test_host"
    model: "csv"
    source: "data/FL/preprocess/vfl/test/host.csv"
  - description: "preprocess_hfl_train_client1"
    model: "csv"
    source: "data/FL/preprocess/hfl/train/client1.csv"
  - description: "preprocess_hfl_test_client1"
    model: "csv"
    source: "data/FL/preprocess/hfl/test/client1.csv"

  # MPC statistics & arithmetic
  - description: "mpc_statistics_1"
    model: "csv"
    source: "data/mpc_test.csv"
  - description: "mpc_arithmetic_1"
    model: "csv"
    source: "data/mpc_arithmetic_1.csv"
  # no meaningful dataset, just used to represent this party
  - description: "FAKE_DATA_PARTY_1"
    model: "csv"
    source: "data/FL/fake.csv"
