{{- range $tmpindex, $app := until ( int $.Values.fusion.num )}} 
{{- $index := add $tmpindex 1 -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: fusion{{ $index }}
  namespace: {{ $.Release.Namespace }}
  labels:
    name: fusion{{ $index }}
  annotations:
    workload: fusion{{ $index }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fusion{{ $index }}
  template:
    metadata:
      labels:
        name: fusion{{ $index }}
    spec:
      containers:
        - name: fusion{{ $index }}
          image: {{ $.Values.fusion.image }}
          env:
            - name: TZ
              value: Asia/Shanghai
          command:
            - java
          args:
            - '-jar'
            - '-Dfile.encoding=UTF-8'
            - /applications/meta.jar
            - '--server.port=8080'
            - '--grpc.server.port=9099'
            - '--spring.cloud.nacos.discovery.server-addr=nacos:8848'
            - '--spring.cloud.nacos.discovery.namespace=demo{{ $index }}'
            - '--spring.cloud.nacos.config.server-addr=nacos:8848'
            - 'spring.cloud.nacos.config.namespace=demo{{ $index }}'
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 10

---
{{- end }}